{% set version = '0.6.15' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-digest
  version: {{ version|replace("-", "_") }}

source:
  fn: digest_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/digest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/digest/digest_{{ version }}.tar.gz
  sha256: 882e74bb4f0722260bd912fd7f8a0fcefcf44c558f43ac8a03d63e53d25444c5

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('digest')"           # [not win]
    - "\"%R%\" -e \"library('digest')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://dirk.eddelbuettel.com/code/digest.html
  license: GPL (>= 2)
  summary: Implementation of a function 'digest()' for the creation  of hash digests of arbitrary
    R objects (using the 'md5', 'sha-1', 'sha-256',  'crc32', 'xxhash' and 'murmurhash'
    algorithms) permitting easy comparison of R language objects, as well as a function
    'hmac()' to create hash-based message authentication code. Please note that this
    package is not meant to be deployed for cryptographic purposes for which more comprehensive
    (and widely tested) libraries such as 'OpenSSL' should be used.
  license_family: GPL3

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: digest
# Author: Dirk Eddelbuettel <edd@debian.org> with contributions  by Antoine Lucas, Jarek Tuszynski, Henrik Bengtsson, Simon Urbanek, Mario Frasca, Bryan Lewis, Murray Stokely, Hannes Muehleisen, Duncan Murdoch, Jim Hester, Wush Wu, Qiang Kou, Thierry Onkelinx,  Michel Lang, Viliam Simko and Kurt Hornik.
# Version: 0.6.15
# Date: 2018-01-28
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Title: Create Compact Hash Digests of R Objects
# Description: Implementation of a function 'digest()' for the creation  of hash digests of arbitrary R objects (using the 'md5', 'sha-1', 'sha-256',  'crc32', 'xxhash' and 'murmurhash' algorithms) permitting easy comparison of R language objects, as well as a function 'hmac()' to create hash-based message authentication code. Please note that this package is not meant to be deployed for cryptographic purposes for which more comprehensive (and widely tested) libraries such as 'OpenSSL' should be used.
# URL: http://dirk.eddelbuettel.com/code/digest.html
# BugReports: https://github.com/eddelbuettel/digest/issues
# Depends: R (>= 2.4.1)
# License: GPL (>= 2)
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2018-01-28 16:42:14.094058 UTC; edd
# Repository: CRAN
# Date/Publication: 2018-01-28 21:43:31 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
