# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HtoXntnyR2HIDuzFJvR0uXHibaM2HyS+IqmDJ8I/df9pj5OGYwa6pWNyNIptjkBui9kIU8F2d1A7V4PF8g4w8NQTzS2Yr9fliv+bOqv5qVs529wUkSMXXnmexr6/exQ/32x70e6RCOy28chLOw8L3ZGttDSxwQSHpe+IoLCacEArfacZ6ASkzf1+pCS2S7++U5Dn4tHERWPlRmx3/2xjJO7n/SscOC5Wst8Xj7BuzN6Ba7VJt2IljzrxDRDQGWqHs5jiDkhBmM93KobFq/IMH5rk7kAxxwQVUKwk1g5zIwOZEUEZ2L3ee99ZfCxzcNkoOyU7HjvhYUrOUVwvYKBUHoEkoelanMUPOxbhqfSSDFnat1jv49/aNddDZVA6+zSGqZNBlxnEsa0KVgGjyKmO9wukodqhe3VabVlrF7BBg+JSr6MHW85g9rHZGtIH8j13vpNuD8zxFNJAOskF1yZkNa3vzZVr5TRryR9t227DfoP3SY/CeUEQ7DKeaEHePR5MvaNGfpQqopvY9qLZCUwY/AavdHwrTaIfmnTtFHpZdCl93tjY4ECLJduDQqKGuj9AKUEocg7fmKEa4El004oBg6EVWRJm1ltDW1UkMGF1Z99bEpLYimwFP+0fmgebGS7s1J4zSqKr8IdJa/wuO1zjhXwaro1gOL0BfS97lj7tNGQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
