travis:
  secure:
    BINSTAR_TOKEN: C5OL+riYxRIYU+3jg57DKPcenc4y8xWFgHLHvEpNz0CJ36mpAm+Xj+zgW3jMVoMEHUFJZT9JygiID1KUwe8qysBxJYWxKgfFJTiNHsJlrapXEqxwJKHLZr0ag22lu3MxZgrvaxUad8uX4xA3SGDzygha5rtF9zXP4kFhYGzW6aXr8C7CQc8M9UKF0Zjs4Q1jd67Q/SStIh5GLEtbN0y+HhS63K/CA7vNhqB8cr+ylXOBFdZYRB71m9hjLMM+3n3VsRKNOV4kI+zjQf9kp1MyWUeOPWNC5Z/LlfuFTTaH6BShaxKC60ogC0F9eDIdK3rfdoH0jyufg4HvOX55SiowH+teC6ZUgL/Jl4/QwaqYBAaNvjl0SF7PKcVITrJF2Cx10JsXNrkyUpeLsGWeyq4Q68ODVh1twaUAwBpOStG6ZtvvwhOpmzWfuKhxOHi5LB4c+4D0AIv4TfORzLCpjEyD0JSXp7csnW4XmZHIN081rOlotXuMjmIWDpRBuq8qZCYuH8EivPXZrjnVNSNVcZzzDALHzfmlwhfLXj3TDE/GvwXEbPXQnTNtGluC3YEBplBvKdJkrj9adLau71OPrvXbYpbTUwkTAY9vSZQJl9kOMUEda3aQrhcDN44jSMJEBeJF3xZHCecnxRUCFsGPGhLtzeUhpHqz24Iili/s3hbUtes=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
