travis:
  secure:
    BINSTAR_TOKEN: WVZHWkTgxkZMwVrt1I8VxP9niTQy7Ex6iMdjaVFi5gET+Rcm4dmQqredCXAy6MmrsO2OIa2QiUCN1B4/INWFRoKfSvdBIUPUkzUH4miG1vsxo8fb+IchRBjrGIZERRMHKnHCOiEeZgpL2iluxSje3Z9mZYPmTKH02e7y0P+s96nZ2kBGQ9vjDKEp2S+Tp6+DEM0ezh57L2aEqmCbssbdiHnnZsGRvgnVYfad9US3GqjPELln3wZNHRIbpGonrpLMASEThj0bCyUzET44PNU2aOU+aYCxCua0ytUVhydhk/OTw3GTVIb4EzhE5GJUn8W2FisATFfYATkoLsuYiDtU+S0paXkuSKFsrAieDqcxGFv3OvPOthuHbTNAykLhR4Iq/ROH8P4s866aviBNNKyFGG1WEMBbCgjnNX1h8mu01Ij+YWBupiFky6dVI65KQspV3xtWGgFVi/iz7WImqyMu4SaT0+YFvOQ1KX0gdC9vV8wlO6MqJlLWOQ9jN+XJRMJ8k+fMC+iHJRzc38vLEh1MR4qswhVeWMuw6BgPy1gAZjtFOGIEdiO4JZSF5jRIP1DkU0OXXmlaZ+sdalBx58UMJohRHwEcSvLstTFRJePH6o00NYpUNdDlsqrOuDyR5eqLZGON/QEtnb8Wa0ygNNmVPFoVeSl7rkAmCC6TCxdO894=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
