travis:
  secure:
    BINSTAR_TOKEN: EMD1wBEbauwrGN66xmZTjOgGCP1rPIzzCTreAHwNrz2FXpA7IE8MymJBn7YMFPbfxC56l9A11FOwq2p0dWPR1+q4JRc5f4MrFNecs6tAPv4+k/hmanY5VG/0pjeTdN107ntLbPT1IZbPrB29MayTpwlpBr2532oR3r0mJMJQFKAJQqbxbUvFKCKzRCDay4IrqAAJYNYkOq3JGGAhQgMHcI+8dEzRommCsuc9sNWNg1HsJSae9LmRUMK4hXvKymsOKSLzR66oecdryZcoiWRxxkl+QTntrZym5E+jTnFUeyc+GOs4SQb8s4Zv6DN4U9hcv45scc11x9iF3whc1XGYJjkr0sJJ0qH/ahDfuNn+m0MopXIr34Psjmsob7K4FFaazlMcpyFiw2+QhJ1VMhPJUH1sAcgCAbIdarGnnpHBq3uIYREXd2hPMKypteaAFRmrQxEOx/CbgXRYXycXbJrVNVZJPS0mLJBkPekWciR0H1oH+JJ1KlE/MFNWbzuOeXkLmo8VeXALcziYB2++SWIhswwQKuYlXyN/kjVWFWHnXmIOS1117mQcMfM67jbqZRY8YlEaZ9OmGu6uK5O1KUXO4XqcD+7clYXRMgonyzCCP32+abGPBdAaCwuU4tts4+cGYL/wbLBf7T95zqB2cOmdO7fRdzXK3Fji00DVefe7LnA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
