travis:
  secure:
    BINSTAR_TOKEN: HtoXntnyR2HIDuzFJvR0uXHibaM2HyS+IqmDJ8I/df9pj5OGYwa6pWNyNIptjkBui9kIU8F2d1A7V4PF8g4w8NQTzS2Yr9fliv+bOqv5qVs529wUkSMXXnmexr6/exQ/32x70e6RCOy28chLOw8L3ZGttDSxwQSHpe+IoLCacEArfacZ6ASkzf1+pCS2S7++U5Dn4tHERWPlRmx3/2xjJO7n/SscOC5Wst8Xj7BuzN6Ba7VJt2IljzrxDRDQGWqHs5jiDkhBmM93KobFq/IMH5rk7kAxxwQVUKwk1g5zIwOZEUEZ2L3ee99ZfCxzcNkoOyU7HjvhYUrOUVwvYKBUHoEkoelanMUPOxbhqfSSDFnat1jv49/aNddDZVA6+zSGqZNBlxnEsa0KVgGjyKmO9wukodqhe3VabVlrF7BBg+JSr6MHW85g9rHZGtIH8j13vpNuD8zxFNJAOskF1yZkNa3vzZVr5TRryR9t227DfoP3SY/CeUEQ7DKeaEHePR5MvaNGfpQqopvY9qLZCUwY/AavdHwrTaIfmnTtFHpZdCl93tjY4ECLJduDQqKGuj9AKUEocg7fmKEa4El004oBg6EVWRJm1ltDW1UkMGF1Z99bEpLYimwFP+0fmgebGS7s1J4zSqKr8IdJa/wuO1zjhXwaro1gOL0BfS97lj7tNGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
