travis:
  secure:
    BINSTAR_TOKEN: xr7G+Gdq4P+N1wO21Xj7dBKgJW9KT+Jq30s43MFDs+0rF4sjj8037ZTBvEUgiwS2N1+o6bAIP5kH8JvY4bgmy99oLqV2w8BhtydovJIKkM65jWAEpP4q5yQi5dXTcb49q5dMdg0Cs5HyS5CmzGlHH8+LWs6MBvyU+mPLOkqDJLLqH7pbzlkNAAf7jOF1nx37ZsrmdYF9Q7sUiXjPc1KJCMQjfZUymGwSPh9h8AluXHG4JXn80chWrQCebCmytp8DhYI3XIvVpqK8XYhqIi0f2SLuTqNDaLBGbXB7v016GMwjyzgwXT8xSqEdFt6rfl8piPmcM39OqkqDC3FluSY4Wf0rus82C9gcGMY4n0ifDPNKBrwFlnGY8oqKWnYkk3FBcoILxOyfJd8xdg9wth6fgfL8x8ctXerSd+j1N9kIRlmP3GA4VhtZwoc3px6swf9omHXhVc1mfg/T0AigHSXp3i8P3YjX2Ebms25YuRM1Qxk28e2JC3kZpgg24rUcLrmx79sIzcZXD6klrN9hIILN0wHFU5LIEPgL6FL4TcXiMOE+uwRYvLiqxm98KELZ292/DwYWw/BuxE5VK81Lv/RTB1IxfqP4Mov6BxkbyKMcboLJTt4gKct92xGTjxBoa9Bipwl9GZP62cuVikjrdPZtOKKY0QldnCnvfwK0e0YO0yY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
